print("Hell World")
print("Hell Again")
print("I like typing this.")
print("This is fun")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("Putting an octothorpe befor a statement creates a comment")